services:
  mongodb:
    image: mongo:latest
    container_name: redback_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: redback_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
